[tool.poetry]
name = "mcml-day2"
version = "0.1.0"
description = "Environment for MCML Workshop Day 2"
authors = ["Alexander Kathan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
